# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 165d75e513c629772d00f74d118dc8927bba23db2af2d5b8e1ab1d546b54beecce128e78e01a41f88de58f54d1726d6b2480f57118b37e772e1b64be421fb88a

test:
  secret_key_base: fb6a1560f7aa65ec8ffd441e43693b786386c5a079e3787b75bfd69b2a1edb08cd0ce79e75774a28cd4b9bf95c951a126de290ac947ee4db8e55c5f7b4f73a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
